# SYNOPSIS:
#
#		make [all] 	- make all targets
#		make TARGET	- make specific target
#		make clean	- remove all files generated by make

# Points to the root of Google Test relative to where this file is.
GTEST_DIR=/usr/local/opt/include/gtest

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $GTEST_DIR/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread -std=c++20

# All Google Test headers. Usually you shouldn't change this
# definition.
GTEST_HEADERS = /usr/local/opt/googletest/include/gtest/*.h \
								/usr/local/opt/googletest/include/gtest/internal/*.h

#All final build targets in this Makefile
TARGETS = run test

all : $(TARGETS)

clean :
	$(RM) $(TARGETS) gtest_main.a *.o

run : main.o conway.o
	$(CXX) -o $@ $^

test : tests.o gtest_main.a conway.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

conway.o : lib/conway.cpp lib/conway.hpp
	$(CXX) -o $@ -c $<

main.o : src/main.cpp lib/conway.hpp
	$(CXX) -o $@ -c $<

tests.o : unit_tests/tests.cpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c unit_tests/tests.cpp

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.

GTEST_SRCS_=/usr/local/opt/googletest/include/googletest/googletest/src/*.cc /usr/local/opt/googletest/include/googletest/googletest/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized. This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I /usr/local/opt/googletest/include/googletest/googletest $(CXXFLAGS) -c \
			/usr/local/opt/googletest/include/googletest/googletest/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I /usr/local/opt/googletest/include/googletest/googletest $(CXXFLAGS) -c \
			/usr/local/opt/googletest/include/googletest/googletest/src/gtest_main.cc
